name: Linux build of Goo Engine

on:
  push:
    branches: [ "goo-engine-main" ]
  pull_request:
    branches: [ "goo-engine-main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Linux or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake git ninja-build
          sudo apt-get install libepoxy-dev

      - name: Clone Blender repository
        run: |
          mkdir -p ${{ github.workspace }}/blender
          cd ${{ github.workspace }}/blender
          git clone https://github.com/blender/blender.git .

      - name: Configure CMake
        run: |
          cd ${{ github.workspace }}/blender
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_NAME=Linux -G "Ninja" ..

      - name: Build
        run: |
          cd ${{ github.workspace }}/blender/build
          cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Create AppImage
        run: |
          cd ${{ github.workspace }}/blender/build
          sudo apt install -y appimagetool
          appimagetool blender ../blender.appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: blender-appimage
          path: ${{ github.workspace }}/blender/blender.appimage
