name: CMake on a single platform

on:
  push:
    branches: [ "goo-engine-main" ]
  pull_request:
    branches: [ "goo-engine-main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Linux or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake git ninja-build
    - name: Clone Blender repository
      run: git clone https://github.com/blender/blender.git
      working-directory: $GITHUB_WORKSPACE/blender

    - name: Configure CMake
      run: cmake -B $GITHUB_WORKSPACE/blender/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_NAME=Linux -G "Ninja"

    - name: Build
      run: cmake --build $GITHUB_WORKSPACE/blender/build --config ${{env.BUILD_TYPE}}

    - name: Create AppImage
      run: |
        sudo apt install -y appimagetool
        appimagetool $GITHUB_WORKSPACE/blender/build/blender $GITHUB_WORKSPACE/blender/blender.appimage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: blender-appimage
        path: $GITHUB_WORKSPACE/blender/blender.appimage
